package campaign

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/osteele/weft/internal/cloud"
	"github.com/osteele/weft/internal/db"
	"github.com/osteele/weft/internal/instanceintent"
	"github.com/osteele/weft/internal/oplog"
	"github.com/osteele/weft/internal/r2"
	"github.com/osteele/weft/internal/r2keys"
)

// InstanceActionKind describes what reconciliation action should be taken.
type InstanceActionKind int

const (
	ActionNone                  InstanceActionKind = iota
	ActionDisplayOnly                              // stall message only, no state change
	ActionGraceExpired                             // grace deadline passed -> destroy + fail
	ActionDonorComplete                            // donor ready marker -> destroy + complete
	ActionTerminationIntent                        // R2 intent -> destroy + mark terminal
	ActionEmptyStatusTimeout                       // stuck with no provider status -> fail
	ActionBootstrapStalled                         // no bootstrap progress -> fail
	ActionBootstrapComplete                        // bootstrap stalled but R2 completion marker found -> complete
	ActionProviderDead                             // provider says dead (with hysteresis) -> fail/complete
	ActionSelfDestructFailed                       // jobs terminal, instance lingering -> finalize launch + destroy
	ActionSetupStalled                             // setup phase unchanged too long -> fail
	ActionRunningStalled                           // running phase + stale heartbeat too long -> fail
	ActionIdleAfterReadyTimeout                    // agent reached ready but never started a job -> fail
	ActionPause                                    // provider stopped instance (preempted / account pause) -> launch=paused
	ActionResume                                   // previously paused launch resumed by provider -> launch=running
	ActionHedgeCull                                // hedge cohort sibling reached ready first -> destroy this loser
	ActionTerminalLivePhase                        // live phase reports running job that is already terminal in DB
)

// graceShutdownTimeout is how long after the grace deadline the coordinator
// waits for the agent to write a termination intent before force-destroying.
// The agent normally self-destructs within seconds of its deadline; this
// timeout is a safety net for unresponsive agents.
const graceShutdownTimeout = 2 * time.Minute

// InstanceAction describes what reconciliation action to take for a cloud instance.
type InstanceAction struct {
	Kind              InstanceActionKind
	TerminalStatus    string // db status to set (failed, completed, "")
	TerminationReason string // reason string for DB
	StallMessage      string // human-readable message
	DestroyProvider   bool   // whether to destroy the provider instance
	ResetJobs         bool   // whether to reset jobs to unplaced
	AttemptOutcome    string // attempt outcome when resetting/closing

	// Provider-state snapshot at the time the action was decided. Carried
	// through to the oplog at ExecuteAction time so post-mortems can see
	// the raw classifier inputs without re-fetching from the provider.
	ObservedProviderStatus         string
	ObservedProviderIntendedStatus string
	ObservedProviderStatusMsg      string
}

// JobState summarizes the aggregate state of jobs associated with a cloud instance.
type JobState struct {
	HasStartedJob    bool
	AllJobsTerminal  bool
	AllJobsCompleted bool
	AllJobsCanceled  bool
	AnyFailed        bool
	AnyOrphaned      bool
	LatestJobEnd     int64 // unix timestamp of latest job end, 0 if none
}

// ComputeJobState computes aggregate job state from a list of jobs.
func ComputeJobState(jobs []*db.Job, outcomes map[int64]string) JobState {
	s := JobState{
		AllJobsTerminal:  true,
		AllJobsCompleted: len(jobs) > 0,
		AllJobsCanceled:  len(jobs) > 0,
	}
	for _, j := range jobs {
		displayStatus := AttemptDisplayStatus(j, outcomes)
		if jobStartedOnInstance(j) {
			s.HasStartedJob = true
		}
		if !IsJobTerminal(displayStatus) {
			s.AllJobsTerminal = false
			s.AllJobsCompleted = false
			s.AllJobsCanceled = false
		} else {
			if displayStatus != db.StatusCompleted {
				s.AllJobsCompleted = false
			}
			if displayStatus != db.StatusCanceled {
				s.AllJobsCanceled = false
			}
			switch displayStatus {
			case db.StatusFailed, db.StatusDead, db.StatusKilled:
				s.AnyFailed = true
			case db.AttemptOutcomeOrphaned:
				s.AnyOrphaned = true
			}
		}
		if j.EndTime != nil && *j.EndTime > s.LatestJobEnd {
			s.LatestJobEnd = *j.EndTime
		}
	}
	return s
}

// jobStartedOnInstance reports whether the job actually executed.
// start_time is the only reliable signal: it is stamped when the agent
// transitions the job to running. end_time alone is NOT sufficient
// because cancel/supersede paths stamp end_time without ever invoking
// the agent — the supersede chains generated by tryPlaceOntoExistingInstances
// on dep-blocked or producer-missing jobs (e.g. 360+ end_time-set
// canceled attempts on a single launch) would otherwise silence the
// bootstrap-stall and idle-after-ready watchdogs (rules 5/5a) for the
// entire life of the launch and let dead instances run indefinitely.
//
// Edge case: a job that completes faster than one sync tick may never
// have its start_time observed. The cost of missing this case is one
// extra watchdog cycle for that launch — strictly preferable to the
// permanent watchdog suppression the end_time check produced.
func jobStartedOnInstance(j *db.Job) bool {
	if j == nil {
		return false
	}
	return j.StartTime > 0
}

func (s JobState) TerminalLaunchStatus() (status string, reason string, ok bool) {
	if !s.HasStartedJob || !s.AllJobsTerminal {
		return "", "", false
	}
	switch {
	case s.AllJobsCompleted:
		return db.LaunchStatusCompleted, db.TerminationReasonCompleted, true
	case s.AllJobsCanceled:
		return db.LaunchStatusCancelled, db.TerminationReasonCancelled, true
	case s.AnyFailed:
		return db.LaunchStatusFailed, db.TerminationReasonJobFailure, true
	case s.AnyOrphaned:
		return db.LaunchStatusFailed, db.TerminationReasonInfraFailure, true
	default:
		return db.LaunchStatusFailed, db.TerminationReasonJobFailure, true
	}
}

// CheckInstanceParams holds all the pre-fetched state needed to evaluate an instance.
type CheckInstanceParams struct {
	CI             *db.Launch
	ProviderInst   *cloud.Instance
	ProviderErr    error
	R2Client       *r2.Client
	JobState       JobState
	PauseTolerant  bool
	InstancePhase  string // reconciled display/check phase
	BootstrapStage string // from R2
	HeartbeatAge   time.Duration
	Heartbeat      *HeartbeatSample
	Now            time.Time

	// TerminationIntent from R2 or DB (pre-fetched by caller)
	TerminationIntent *instanceintent.Marker

	// BootstrapSurvival holds adaptive bootstrap thresholds from historical
	// survival analysis. Nil means use package defaults.
	BootstrapSurvival *db.BootstrapSurvival

	// PhaseChangedAt is when the current InstancePhase was first observed.
	// Nil means unknown (phase stall check is skipped).
	PhaseChangedAt *time.Time

	// LastProviderStatusChangeAt is the time of the most recent
	// provider_status_transitions row for this launch. Used to anchor
	// rule 4b's pre-running timeout on time-since-status-went-non-running
	// instead of launched_at, so a previously-running instance gets a
	// fresh deadline when it transitions to a non-running status.
	// Nil means unknown — falls back to lifecycle start.
	LastProviderStatusChangeAt *time.Time

	// SetupSurvival holds adaptive setup-phase thresholds from historical
	// survival analysis. Nil means use package defaults.
	SetupSurvival *db.SetupSurvival

	// HedgeCohortHasReadySibling reports whether another launch in this
	// launch's hedge cohort has reached agent_ready. Pre-computed by the
	// caller because CheckInstance must stay pure (no DB handle).
	HedgeCohortHasReadySibling bool

	// OnStartProbePresent is true when the OnStart script's first-line
	// probe (a curl PUT to the presigned URL) has landed in R2. The
	// probe is the earliest evidence the container actually executed
	// OnStart with outbound network. Used by the dud-provider watchdog
	// (rule 4d) to distinguish "provider says running but container never
	// started" from "container running, OnStart in flight".
	OnStartProbePresent bool

	// BootstrapActivitySeen is true when current or historical bootstrap
	// stage data exists for the launch. It protects the dud-provider
	// watchdog from false-firing on transient empty R2 reads after
	// bootstrap has already shown progress.
	BootstrapActivitySeen bool

	// RunningPhaseJobTerminalSince is set when InstancePhase reports
	// running:<job> but that job's attempt on this launch is already
	// terminal in the DB. A fresh heartbeat can otherwise keep a dead
	// launch alive forever while queued attempts stay attached to it.
	RunningPhaseJobID            int64
	RunningPhaseJobStatus        string
	RunningPhaseJobTerminalSince *time.Time
}

// CheckInstance evaluates what reconciliation action should be taken for a
// single cloud instance. This is the single source of truth for all instance
// reconciliation decisions. It does not mutate state, but may perform read-only
// R2 queries (donor ready check, completion marker).
//
// Hysteresis state (dead confirmation, probe failures) is tracked on the
// Reconciler. For WatchInstance, use a per-goroutine Reconciler.
func (r *Reconciler) CheckInstance(p CheckInstanceParams) (action InstanceAction) {
	ci := p.CI
	if ci == nil {
		return InstanceAction{Kind: ActionNone}
	}

	// Stamp the provider snapshot onto every non-no-op action so
	// ExecuteAction can record it in the oplog.
	defer func() {
		if action.Kind == ActionNone || action.Kind == ActionDisplayOnly || p.ProviderInst == nil {
			return
		}
		action.ObservedProviderStatus = p.ProviderInst.Status
		action.ObservedProviderIntendedStatus = p.ProviderInst.IntendedStatus
		action.ObservedProviderStatusMsg = p.ProviderInst.StatusMsg
	}()

	// 1. Grace expiry: deadline has passed.
	// The instance entered grace because a job failed. Don't reset jobs to
	// queued (ResetJobs: false) — the job already ran and errored, so
	// re-queuing would cause an infinite retry loop. Close the attempts as
	// "failed" instead.
	//
	// Instead of immediately destroying, we give the agent time to shut down
	// gracefully (upload logs, write termination intent). The coordinator
	// only force-destroys after graceShutdownTimeout with no agent response.
	if ci.Status == db.LaunchStatusGrace && ci.GraceDeadline != nil && p.Now.Unix() > *ci.GraceDeadline {
		if p.TerminationIntent != nil {
			// Agent already signaled intent to shut down — fall through
			// to step 3 which handles termination intent properly.
		} else {
			graceOverdueBy := p.Now.Sub(time.Unix(*ci.GraceDeadline, 0))
			if graceOverdueBy > graceShutdownTimeout {
				return InstanceAction{
					Kind:              ActionGraceExpired,
					TerminalStatus:    db.LaunchStatusFailed,
					TerminationReason: db.TerminationReasonJobFailure,
					StallMessage:      fmt.Sprintf("grace period expired %s ago with no agent shutdown — force terminating", graceOverdueBy.Truncate(time.Second)),
					DestroyProvider:   true,
					AttemptOutcome:    db.AttemptOutcomeFailed,
				}
			}
			return InstanceAction{
				Kind:         ActionDisplayOnly,
				StallMessage: "grace period expired — waiting for agent shutdown",
			}
		}
	}

	// 1a. Hedge-cohort cull: a non-survivor probe is terminated once a
	// sibling reaches agent_ready. Gate on AgentReadyAtUnix == nil so
	// the survivor itself is never the one culled. ResetJobs orphans
	// any jobs the loser was holding so the next reuse pass migrates
	// them onto the surviving probe.
	// See campaign-lifecycle.allium § HedgeCohortCull.
	if ci.HedgeCohortID != nil && ci.AgentReadyAtUnix == nil &&
		(ci.Status == db.LaunchStatusLaunching || ci.Status == db.LaunchStatusRunning) &&
		p.HedgeCohortHasReadySibling {
		return InstanceAction{
			Kind:              ActionHedgeCull,
			TerminalStatus:    db.LaunchStatusCancelled,
			TerminationReason: db.TerminationReasonCancelled,
			StallMessage:      "hedge cohort sibling reached ready first — culling",
			DestroyProvider:   true,
			ResetJobs:         true,
			AttemptOutcome:    db.AttemptOutcomeCancelled,
		}
	}

	// 2. Donor completion
	if ci.InstanceRole == "donor" && ci.Status == db.LaunchStatusRunning && p.R2Client != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		exists, _ := p.R2Client.ObjectExists(ctx, r2keys.DonorReady(ci.ID))
		cancel()
		if exists {
			return InstanceAction{
				Kind:              ActionDonorComplete,
				TerminalStatus:    db.LaunchStatusCompleted,
				TerminationReason: db.TerminationReasonCompleted,
				DestroyProvider:   true,
			}
		}
	}

	// 3. Termination intent from R2/DB
	if p.TerminationIntent != nil {
		if action := r.checkTerminationIntent(ci, p.ProviderInst, p.TerminationIntent, p.PauseTolerant); action.Kind != ActionNone {
			return action
		}
	}

	// 3a. The heartbeat sidecar is alive, but it reports that the campaign
	// agent process has exited. Treat this as a genuine agent death instead of
	// waiting for the heartbeat object to go stale.
	if ci.Status == db.LaunchStatusRunning && p.Heartbeat != nil && p.Heartbeat.AgentAlive != nil && !*p.Heartbeat.AgentAlive {
		stallMessage := "campaign agent exited while instance was still running — terminating instance"
		if p.Heartbeat.AgentFatal != "" {
			stallMessage = "campaign agent panicked: " + p.Heartbeat.AgentFatal + " — terminating instance"
		}
		return InstanceAction{
			Kind:              ActionRunningStalled,
			TerminalStatus:    db.LaunchStatusFailed,
			TerminationReason: db.TerminationReasonInfraFailure,
			StallMessage:      stallMessage,
			DestroyProvider:   true,
			ResetJobs:         true,
			AttemptOutcome:    db.AttemptOutcomeOrphaned,
		}
	}

	// 3b. Impossible live phase: the sidecar/phase marker is fresh and claims
	// a job is running, but the DB already has that launch attempt in a
	// terminal state. Treat this as an unhealthy agent/phase loop and orphan
	// the remaining queued attempts so they can be placed elsewhere.
	if ci.Status == db.LaunchStatusRunning && p.RunningPhaseJobTerminalSince != nil {
		age := p.Now.Sub(*p.RunningPhaseJobTerminalSince)
		if age > 2*time.Minute {
			status := strings.TrimSpace(p.RunningPhaseJobStatus)
			if status == "" {
				status = "terminal"
			}
			reason := db.TerminationReasonInfraFailure
			switch status {
			case db.StatusFailed, db.StatusDead, db.StatusKilled:
				reason = db.TerminationReasonJobFailure
			}
			return InstanceAction{
				Kind:              ActionTerminalLivePhase,
				TerminalStatus:    db.LaunchStatusFailed,
				TerminationReason: reason,
				StallMessage:      fmt.Sprintf("live phase reports wj%d running, but its attempt is %s for %s — terminating instance", p.RunningPhaseJobID, status, age.Truncate(time.Second)),
				DestroyProvider:   true,
				ResetJobs:         true,
				AttemptOutcome:    db.AttemptOutcomeOrphaned,
			}
		}
	}

	// 4. Empty provider status timeout
	if p.ProviderInst != nil && p.ProviderInst.Status == "" {
		if lifecycleStart := cloudInstanceLifecycleStart(ci); lifecycleStart != nil {
			age := p.Now.Sub(*lifecycleStart)
			if age > maxEmptyStatusTime {
				return InstanceAction{
					Kind:              ActionEmptyStatusTimeout,
					TerminalStatus:    db.LaunchStatusFailed,
					TerminationReason: db.TerminationReasonInfraFailure,
					StallMessage:      "provider instance has empty status — terminating",
					DestroyProvider:   true,
					ResetJobs:         true,
					AttemptOutcome:    db.AttemptOutcomeOrphaned,
				}
			}
		}
	}

	// 4a. Stale-agent watchdog. Heartbeat-first liveness: an agent that
	// reached ready and then stopped writing heartbeats is functionally
	// dead. Provider liveness is handled by separate rules because provider
	// list results can be stale or temporarily incomplete.
	//
	// Cases not covered here:
	//   - Bootstrap-never-completed (no agent_ready_at_unix ever set):
	//     caught by the bootstrap-deadline watchdog (rule 5).
	//   - Provider explicitly reports terminal status (exited, destroyed,
	//     etc.): caught by rule 7 (provider_dead with hysteresis).
	if ci.Status == db.LaunchStatusRunning && ci.AgentReadyAtUnix != nil &&
		p.HeartbeatAge > effectiveHeartbeatStaleThreshold(ci.AgentReadyAtUnix, p.Now) {
		// Yield to rule 4a-pause only when the provider status is expected to
		// resume. Vast "offline" is resumable for interruptible placements, but
		// for on-demand placements it is provider-dead evidence and should not
		// mask a stale heartbeat.
		if p.ProviderInst == nil || !isRecoverablePausedProviderStatus(p.ProviderInst.Status, p.PauseTolerant) {
			return InstanceAction{
				Kind:              ActionEmptyStatusTimeout,
				TerminalStatus:    db.LaunchStatusFailed,
				TerminationReason: db.TerminationReasonInfraFailure,
				StallMessage:      fmt.Sprintf("agent heartbeat stale for %s — terminating", p.HeartbeatAge.Truncate(time.Second)),
				DestroyProvider:   true,
				ResetJobs:         true,
				AttemptOutcome:    db.AttemptOutcomeOrphaned,
			}
		}
	}

	// 4a-resume. Previously paused launch is now running again at the provider.
	if ci.Status == db.LaunchStatusPaused && p.ProviderInst != nil &&
		p.ProviderInst.Status == cloud.ProviderStatusRunning {
		return InstanceAction{
			Kind:         ActionResume,
			StallMessage: "instance resumed by provider",
		}
	}

	// 4a-pause. Provider paused the instance. Vast.ai reports interruptible
	// preemption as "offline"; stopped covers explicit provider pauses such as
	// account/credit holds. Only pause statuses that can reasonably resume are
	// reflected as LaunchStatusPaused.
	if p.ProviderInst != nil && isRecoverablePausedProviderStatus(p.ProviderInst.Status, p.PauseTolerant) {
		if lifecycleStart := cloudInstanceLifecycleStart(ci); lifecycleStart != nil {
			age := p.Now.Sub(*lifecycleStart)
			if age > stalePauseTimeout {
				reason := db.TerminationReasonPreempted
				outcome := db.AttemptOutcomePreempted
				if !p.PauseTolerant {
					reason = db.TerminationReasonProviderFailure
					outcome = db.AttemptOutcomeOrphaned
				}
				return InstanceAction{
					Kind:              ActionEmptyStatusTimeout,
					TerminalStatus:    db.LaunchStatusFailed,
					TerminationReason: reason,
					StallMessage:      fmt.Sprintf("instance %s for %s with no resume — giving up", p.ProviderInst.Status, age.Truncate(time.Minute)),
					DestroyProvider:   true,
					ResetJobs:         true,
					AttemptOutcome:    outcome,
				}
			}
		}
		if ci.Status != db.LaunchStatusPaused {
			return InstanceAction{
				Kind:         ActionPause,
				StallMessage: fmt.Sprintf("provider reports %s instance — marking paused", p.ProviderInst.Status),
			}
		}
		return InstanceAction{
			Kind:         ActionDisplayOnly,
			StallMessage: fmt.Sprintf("provider reports %s instance; waiting for resume/replacement", p.ProviderInst.Status),
		}
	}

	// 4b. Stale non-running status. Anchored on the most recent provider
	// status transition (or lifecycle start when no transitions are
	// recorded), so a previously-running instance that drops back to a
	// non-running state gets a fresh deadline rather than inheriting an
	// already-exceeded one. Skip when IntendedStatus already signals
	// termination — step 8 catches that faster.
	if p.ProviderInst != nil && p.ProviderInst.Status != cloud.ProviderStatusRunning && p.ProviderInst.Status != "" &&
		!isProviderTerminalWithPolicy(p.ProviderInst, p.PauseTolerant) {
		if anchor := stalePreRunningAnchor(ci, p.LastProviderStatusChangeAt); anchor != nil {
			age := p.Now.Sub(*anchor)
			if age > maxPreRunningStatusTime {
				return InstanceAction{
					Kind:              ActionEmptyStatusTimeout,
					TerminalStatus:    db.LaunchStatusFailed,
					TerminationReason: db.TerminationReasonInfraFailure,
					StallMessage:      fmt.Sprintf("provider instance stuck in %q status for %s — terminating", p.ProviderInst.Status, age.Truncate(time.Second)),
					DestroyProvider:   true,
					ResetJobs:         true,
					AttemptOutcome:    db.AttemptOutcomeOrphaned,
				}
			}
		}
	}

	// 4c. Launching phase catch-all: no BootstrapOrigin means rule 5 and
	// spec BootstrapTimeout can't anchor. Fire on CreatedAt; reason
	// infra_failure so the retry path applies. See spec LaunchingPhaseTimeout.
	if ci.Status == db.LaunchStatusLaunching && ci.BootstrapOrigin() == nil {
		if start := cloudInstanceLifecycleStart(ci); start != nil && p.Now.Sub(*start) >= launchingPhaseTimeout {
			return InstanceAction{
				Kind:              ActionEmptyStatusTimeout,
				TerminalStatus:    db.LaunchStatusFailed,
				TerminationReason: db.TerminationReasonInfraFailure,
				StallMessage:      fmt.Sprintf("launching phase exceeded %s with no provider progress — terminating", launchingPhaseTimeout),
				DestroyProvider:   true,
				ResetJobs:         true,
				AttemptOutcome:    db.AttemptOutcomeOrphaned,
			}
		}
	}

	// 4d. Dud-provider detection. The provider reports the rental as `running`
	// (LaunchedAt is set), but no agent activity has appeared in R2
	// after dudVastTimeout: no OnStart probe, no heartbeat, no phase,
	// no current or historical bootstrap stage. This is a host-level binary failure
	// signature (zombie offer, wedged docker daemon, image-pull block)
	// and would otherwise wait the full adaptive bootstrap deadline
	// (often 90+ min). The full conjunction is intentional: any single
	// signal of life means a downstream rule (heartbeat-stale,
	// bootstrap-stalled) is the right adjudicator.
	// See campaign-lifecycle.allium § DudVastDetection.
	if ci.Status == db.LaunchStatusRunning &&
		ci.LaunchedAt != nil && *ci.LaunchedAt > 0 &&
		ci.AgentReadyAtUnix == nil &&
		!p.OnStartProbePresent &&
		!p.BootstrapActivitySeen &&
		p.HeartbeatAge == 0 &&
		p.InstancePhase == "" &&
		p.BootstrapStage == "" {
		runningAt := time.Unix(*ci.LaunchedAt, 0)
		if p.Now.Sub(runningAt) >= dudVastTimeout {
			return InstanceAction{
				Kind:              ActionEmptyStatusTimeout,
				TerminalStatus:    db.LaunchStatusFailed,
				TerminationReason: db.TerminationReasonInfraFailure,
				StallMessage:      fmt.Sprintf("dud provider: %s post-running with no agent activity — terminating instance, jobs reset to queued", p.Now.Sub(runningAt).Truncate(time.Second)),
				DestroyProvider:   true,
				ResetJobs:         true,
				AttemptOutcome:    db.AttemptOutcomeOrphaned,
			}
		}
	}

	// 5. Bootstrap stall: no job progress past the per-launch deadline.
	// Fires during `running` (post-bootstrap wait) and `launching`. The
	// deadline is set once at LaunchInstance time and backfilled for
	// pre-#4 rows (specs/job-move.allium § InstanceReadiness); the
	// reconciler also honors later adaptive survival thresholds so already
	// running launches are not killed by an older, shorter stamped deadline.
	bootstrapPhaseActive := ci.Status == db.LaunchStatusRunning || ci.Status == db.LaunchStatusLaunching
	if bootstrapPhaseActive && strings.HasPrefix(strings.TrimSpace(p.BootstrapStage), "failed:") && !p.JobState.HasStartedJob {
		return InstanceAction{
			Kind:              ActionBootstrapStalled,
			TerminalStatus:    db.LaunchStatusFailed,
			TerminationReason: db.TerminationReasonInfraFailure,
			StallMessage:      fmt.Sprintf("bootstrap failed at %s — terminating instance, jobs reset to queued", BootstrapStageLabel(p.BootstrapStage)),
			DestroyProvider:   true,
			ResetJobs:         true,
			AttemptOutcome:    db.AttemptOutcomeOrphaned,
		}
	}
	if bootstrapPhaseActive && ci.BootstrapDeadlineUnix != nil && !p.JobState.HasStartedJob && p.InstancePhase == "" && p.BootstrapStage != bootstrapStageReady {
		deadline := time.Unix(*ci.BootstrapDeadlineUnix, 0)
		warnTimeout := bootstrapWarnTimeout
		termTimeout := BootstrapTerminateTimeout
		if p.BootstrapSurvival != nil {
			if p.BootstrapSurvival.WarnAfter > 0 {
				warnTimeout = p.BootstrapSurvival.WarnAfter
			}
			if p.BootstrapSurvival.TerminateAfter > 0 {
				termTimeout = p.BootstrapSurvival.TerminateAfter
			}
			if originUnix := ci.BootstrapOrigin(); originUnix != nil {
				learnedDeadline := time.Unix(*originUnix, 0).Add(termTimeout)
				if learnedDeadline.After(deadline) {
					deadline = learnedDeadline
				}
			}
		}
		remaining := deadline.Sub(p.Now)
		warnRemaining := termTimeout - warnTimeout
		if remaining <= warnRemaining {
			// Check R2 completion marker only past the warn threshold,
			// to avoid an R2 call on every reconciliation tick.
			if hasR2CompletionMarker(p.R2Client, ci.ID) {
				return InstanceAction{
					Kind:            ActionBootstrapComplete,
					TerminalStatus:  db.LaunchStatusCompleted,
					StallMessage:    "instance completed but self-destruct failed — cleaning up",
					DestroyProvider: true,
				}
			}
			stageLabel := strings.TrimSpace(BootstrapStageLabel(p.BootstrapStage))
			if stageLabel == "" || p.BootstrapStage == bootstrapStageReady {
				stageLabel = "bootstrap"
			}
			if remaining <= 0 {
				elapsed := termTimeout - remaining
				return InstanceAction{
					Kind:              ActionBootstrapStalled,
					TerminalStatus:    db.LaunchStatusFailed,
					TerminationReason: db.TerminationReasonBootstrapTimeout,
					StallMessage:      fmt.Sprintf("%s timeout after %s — terminating instance, jobs reset to queued", stageLabel, elapsed.Truncate(time.Second)),
					DestroyProvider:   true,
					ResetJobs:         true,
					AttemptOutcome:    db.AttemptOutcomeOrphaned,
				}
			}
			return InstanceAction{
				Kind:         ActionDisplayOnly,
				StallMessage: fmt.Sprintf("%s stalled — no activity (terminating in %s)", stageLabel, remaining.Truncate(time.Second)),
			}
		}
	}

	// 5a. Idle after agent_ready: ready but no job ever started — see
	// idleAfterReadyTimeout doc for the watchdog dead-zone this closes.
	if ci.Status == db.LaunchStatusRunning && ci.AgentReadyAtUnix != nil &&
		!p.JobState.HasStartedJob && p.InstancePhase == "" {
		readyAge := p.Now.Sub(time.Unix(*ci.AgentReadyAtUnix, 0))
		if readyAge >= idleAfterReadyTimeout {
			return InstanceAction{
				Kind:              ActionIdleAfterReadyTimeout,
				TerminalStatus:    db.LaunchStatusFailed,
				TerminationReason: db.TerminationReasonInfraFailure,
				StallMessage:      fmt.Sprintf("agent reached ready %s ago but never started a job — terminating instance, jobs reset to queued", readyAge.Truncate(time.Second)),
				DestroyProvider:   true,
				ResetJobs:         true,
				AttemptOutcome:    db.AttemptOutcomeOrphaned,
			}
		}
	}

	// 5b. Setup phase stall: instance in setup/warmup phase for too long.
	// Running is DB-authoritative via phase reconciliation, so setup checks
	// only apply when reconciled phase is still setup/warmup.
	if ci.Status == db.LaunchStatusRunning {
		verb, _, _ := ParsePhaseJobID(p.InstancePhase)
		if verb == PhaseSetup || verb == PhaseGPUWarmup {
			phaseStart := p.PhaseChangedAt
			if phaseStart == nil {
				// Fallback for legacy rows where phase_changed_at was never recorded.
				phaseStart = cloudInstanceLifecycleStart(ci)
			}
			if phaseStart != nil {
				phaseAge := p.Now.Sub(*phaseStart)

				warnTimeout := defaultSetupStallWarn
				termTimeout := defaultSetupStallTerminate
				if p.SetupSurvival != nil {
					warnTimeout = p.SetupSurvival.WarnAfter
					termTimeout = p.SetupSurvival.TerminateAfter
				}

				if phaseAge >= termTimeout {
					return InstanceAction{
						Kind:              ActionSetupStalled,
						TerminalStatus:    db.LaunchStatusFailed,
						TerminationReason: db.TerminationReasonPhaseStall,
						StallMessage:      fmt.Sprintf("setup phase stalled for %s — terminating instance", phaseAge.Truncate(time.Second)),
						DestroyProvider:   true,
						ResetJobs:         true,
						AttemptOutcome:    db.AttemptOutcomeOrphaned,
					}
				}
				if phaseAge >= warnTimeout {
					remaining := termTimeout - phaseAge
					return InstanceAction{
						Kind:         ActionDisplayOnly,
						StallMessage: fmt.Sprintf("setup phase stalled for %s (terminating in %s)", phaseAge.Truncate(time.Second), remaining.Truncate(time.Second)),
					}
				}
			}
		}
	}

	// 5c. Running phase stall: heartbeat stale while in running phase.
	// A running job with a dead agent (stale heartbeat) should be terminated.
	// This does NOT check GPU utilization — jobs may legitimately not use the GPU.
	if ci.Status == db.LaunchStatusRunning && p.HeartbeatAge > effectiveHeartbeatStaleThreshold(ci.AgentReadyAtUnix, p.Now) {
		verb, _, _ := ParsePhaseJobID(p.InstancePhase)
		if verb == PhaseRunning {
			phaseAge := p.HeartbeatAge
			if p.PhaseChangedAt != nil {
				phaseAge = p.Now.Sub(*p.PhaseChangedAt)
			}
			if phaseAge >= runningStaleTerminate {
				return InstanceAction{
					Kind:              ActionRunningStalled,
					TerminalStatus:    db.LaunchStatusFailed,
					TerminationReason: db.TerminationReasonPhaseStall,
					StallMessage:      fmt.Sprintf("running phase stalled for %s with stale heartbeat — terminating instance", phaseAge.Truncate(time.Second)),
					DestroyProvider:   true,
					ResetJobs:         true,
					AttemptOutcome:    db.AttemptOutcomeOrphaned,
				}
			}
			if phaseAge >= runningStaleWarn {
				remaining := runningStaleTerminate - phaseAge
				return InstanceAction{
					Kind:         ActionDisplayOnly,
					StallMessage: fmt.Sprintf("running phase stalled for %s with stale heartbeat (terminating in %s)", phaseAge.Truncate(time.Second), remaining.Truncate(time.Second)),
				}
			}
		}
	}

	// 6. Failed self-destruct: jobs reached a terminal state but the instance is lingering.
	if ci.Status == db.LaunchStatusRunning && p.JobState.HasStartedJob && p.JobState.AllJobsTerminal {
		if terminalStatus, reason, ok := p.JobState.TerminalLaunchStatus(); ok {
			var sinceEnd time.Duration
			if p.JobState.LatestJobEnd > 0 {
				sinceEnd = p.Now.Sub(time.Unix(p.JobState.LatestJobEnd, 0))
			} else {
				// end_time unknown (was 0) — use a conservative fallback
				sinceEnd = 3 * time.Minute
			}
			if sinceEnd > 2*time.Minute {
				return InstanceAction{
					Kind:              ActionSelfDestructFailed,
					TerminalStatus:    terminalStatus,
					TerminationReason: reason,
					StallMessage:      "jobs reached terminal state but self-destruct failed — cleaning up",
					DestroyProvider:   true,
				}
			}
		}
	}

	// 7. Provider dead detection (with hysteresis)
	// Skip grace-period instances — a transient API failure shouldn't kill the session.
	if p.ProviderErr == nil && isProviderTerminalWithPolicy(p.ProviderInst, p.PauseTolerant) && !IsInstanceTerminal(ci.Status) && ci.Status != db.LaunchStatusGrace {
		var instDescr string
		if p.ProviderInst == nil {
			instDescr = "<nil>"
		} else {
			instDescr = fmt.Sprintf("status=%q intended=%q providerID=%q", p.ProviderInst.Status, p.ProviderInst.IntendedStatus, p.ProviderInst.ProviderID)
		}
		slog.Debug("reconcile: entering provider_dead path", "component", "reconcile", "instance", ci.ID, "inst", instDescr, "ci_status", ci.Status)
		return r.checkProviderDead(ci, p.ProviderInst, p.R2Client, p.JobState, p.Now, p.PauseTolerant)
	}
	// Definitive live signal: provider returned a non-terminal instance. Reset
	// any in-flight dead-confirm timer so the hysteresis requires a fresh
	// stretch of dead observations rather than inheriting an old one. Without
	// this, an instance that flickers (alive, dead, alive, dead) over
	// confirmTime would be marked dead on the second dead observation.
	if p.ProviderErr == nil && p.ProviderInst != nil && !isProviderTerminalWithPolicy(p.ProviderInst, p.PauseTolerant) {
		r.mu.Lock()
		delete(r.firstDeadAt, ci.ID)
		r.mu.Unlock()
	}

	// 8. Stale heartbeat (display-only warning — the reconciler's probe logic is separate)
	if p.HeartbeatAge > effectiveHeartbeatStaleThreshold(ci.AgentReadyAtUnix, p.Now) && ci.Status == db.LaunchStatusRunning {
		return InstanceAction{
			Kind:         ActionDisplayOnly,
			StallMessage: "heartbeat stale",
		}
	}

	return InstanceAction{Kind: ActionNone}
}

func (r *Reconciler) checkTerminationIntent(ci *db.Launch, inst *cloud.Instance, intent *instanceintent.Marker, pauseTolerant bool) InstanceAction {
	if intent == nil {
		return InstanceAction{Kind: ActionNone}
	}

	reason := intent.TerminationReason
	switch intent.TerminalStatus {
	case db.LaunchStatusCompleted:
		if reason == "" {
			reason = db.TerminationReasonCompleted
		}
		return InstanceAction{
			Kind:              ActionTerminationIntent,
			TerminalStatus:    db.LaunchStatusCompleted,
			TerminationReason: reason,
			DestroyProvider:   !isProviderTerminalWithPolicy(inst, pauseTolerant),
			AttemptOutcome:    db.AttemptOutcomeCompleted,
		}
	case db.LaunchStatusFailed:
		if reason == "" {
			reason = db.TerminationReasonJobFailure
		}
		return InstanceAction{
			Kind:              ActionTerminationIntent,
			TerminalStatus:    db.LaunchStatusFailed,
			TerminationReason: reason,
			DestroyProvider:   !isProviderTerminalWithPolicy(inst, pauseTolerant),
			ResetJobs:         true,
			AttemptOutcome:    db.AttemptOutcomeOrphaned,
		}
	default:
		return InstanceAction{Kind: ActionNone}
	}
}

func (r *Reconciler) checkProviderDead(ci *db.Launch, inst *cloud.Instance, r2Client *r2.Client, jobState JobState, now time.Time, pauseTolerant bool) InstanceAction {
	// Check R2 for completion marker before assuming failure.
	if hasR2CompletionMarker(r2Client, ci.ID) {
		slog.Debug("provider dead: found R2 completion marker",
			"component", "reconcile", "instance", ci.ID)
		r.mu.Lock()
		delete(r.firstDeadAt, ci.ID)
		r.mu.Unlock()
		return InstanceAction{
			Kind:              ActionProviderDead,
			TerminalStatus:    db.LaunchStatusCompleted,
			TerminationReason: db.TerminationReasonCompleted,
			AttemptOutcome:    db.AttemptOutcomeCompleted,
		}
	}

	// Check R2 termination intent — the agent may have written it before dying.
	// This catches the race where the agent writes the intent, self-destructs,
	// and the provider shows "exited" before the reconciler's step 3 picks it up.
	if intent, err := fetchReconcileTerminationIntent(context.Background(), r2Client, ci.ID); err == nil && intent != nil {
		if action := r.checkTerminationIntent(ci, inst, intent, false); action.Kind != ActionNone {
			slog.Debug("provider dead: found termination intent",
				"component", "reconcile", "instance", ci.ID,
				"intent_status", intent.TerminalStatus, "intent_reason", intent.TerminationReason)
			r.mu.Lock()
			delete(r.firstDeadAt, ci.ID)
			r.mu.Unlock()
			return action
		}
	}

	// Require the instance to appear dead for confirmTime before declaring terminal.
	confirmTime := r.confirmTime()
	r.mu.Lock()
	first, seen := r.firstDeadAt[ci.ID]
	if !seen {
		r.firstDeadAt[ci.ID] = now
		r.mu.Unlock()
		if confirmTime > 0 {
			return InstanceAction{Kind: ActionNone} // waiting to confirm
		}
	} else {
		r.mu.Unlock()
	}
	if confirmTime > 0 && now.Sub(first) < confirmTime {
		return InstanceAction{Kind: ActionNone} // still confirming
	}
	r.mu.Lock()
	delete(r.firstDeadAt, ci.ID)
	r.mu.Unlock()

	if terminalStatus, reason, ok := jobState.TerminalLaunchStatus(); ok {
		return InstanceAction{
			Kind:              ActionProviderDead,
			TerminalStatus:    terminalStatus,
			TerminationReason: reason,
		}
	}

	// Use "unknown" as the default reason — we can't determine what happened.
	// R2 markers may override below with a more specific reason.
	reason := db.TerminationReasonUnknown
	outcome := db.AttemptOutcomeOrphaned
	if ci.LaunchedAt != nil {
		if pauseTolerant && inst != nil && inst.Status == cloud.ProviderStatusExited {
			reason = db.TerminationReasonPreempted
			outcome = db.AttemptOutcomePreempted
		} else {
			reason = db.TerminationReasonProviderFailure
		}
	}
	reasonAfterR2 := failureTerminationReasonFromR2(context.Background(), r2Client, ci.ID, reason)
	if reasonAfterR2 != reason && reasonAfterR2 != db.TerminationReasonPreempted {
		outcome = db.AttemptOutcomeOrphaned
	}
	detail := buildProviderDeadDetail(ci, inst, reason, reasonAfterR2, now)

	slog.Warn("provider dead: no completion marker or termination intent found, resetting jobs",
		"component", "reconcile", "instance", ci.ID, "reason", reasonAfterR2, "detail", detail)
	return InstanceAction{
		Kind:              ActionProviderDead,
		TerminalStatus:    db.LaunchStatusFailed,
		TerminationReason: reasonAfterR2,
		StallMessage:      detail,
		ResetJobs:         true,
		AttemptOutcome:    outcome,
	}
}

// buildProviderDeadDetail summarises the evidence the classifier had at the
// point where it marked an instance failed without a completion marker or
// termination intent. Intended for the launches.termination_detail column
// and operator-facing logs: the post-mortem otherwise has nothing to say
// beyond "termination_reason=unknown".
func buildProviderDeadDetail(ci *db.Launch, inst *cloud.Instance, baseReason, finalReason string, now time.Time) string {
	parts := []string{"provider dead with no completion or intent marker"}
	if inst == nil {
		parts = append(parts, "provider returned no instance")
	} else if inst.Status == "" {
		parts = append(parts, "provider status empty")
	} else {
		parts = append(parts, fmt.Sprintf("provider status=%s", inst.Status))
	}
	if ci != nil && ci.LaunchedAt != nil {
		parts = append(parts, fmt.Sprintf("launched %s ago", now.Sub(time.Unix(*ci.LaunchedAt, 0)).Truncate(time.Second)))
	}
	if ci != nil && ci.AgentReadyAtUnix != nil {
		parts = append(parts, fmt.Sprintf("agent ready %s ago", now.Sub(time.Unix(*ci.AgentReadyAtUnix, 0)).Truncate(time.Second)))
	} else {
		parts = append(parts, "agent never reported ready")
	}
	if finalReason != baseReason {
		parts = append(parts, fmt.Sprintf("R2 marker refined reason %s→%s", baseReason, finalReason))
	} else {
		parts = append(parts, "no R2 disk-failure marker")
	}
	return strings.Join(parts, "; ")
}

// ExecuteAction performs the side effects described by an InstanceAction: destroying
// the provider instance, updating DB status, and resetting/closing job attempts.
// Returns (reconciled, terminated).
func ExecuteAction(database *sql.DB, client cloud.Client, ci *db.Launch, action InstanceAction) (bool, bool) {
	if action.Kind == ActionNone || action.Kind == ActionDisplayOnly {
		return false, false
	}

	// Pause/resume are non-terminal status flips; no destroy, no job reset.
	if action.Kind == ActionPause || action.Kind == ActionResume {
		newStatus := db.LaunchStatusPaused
		op := oplog.OpLaunchPaused
		if action.Kind == ActionResume {
			newStatus = db.LaunchStatusRunning
			op = oplog.OpLaunchResumed
		}
		if err := db.UpdateLaunchStatus(database, ci.ID, newStatus, "", action.StallMessage); err != nil {
			slog.Warn("failed to update instance status", "component", "reconcile", "instance", ci.ID, "status", newStatus, "error", err)
			return false, false
		}
		oplog.Log(op, oplog.WithDetail(formatActionDetail(ci.ID, action)))
		if eventKind := actionEventKind(action.Kind); eventKind != "" {
			_ = db.InsertLifecycleEvent(database, &db.LifecycleEvent{
				EventKind: eventKind,
				LaunchID:  ci.ID,
				GPUSpec:   ci.GPUSpec,
				Detail:    action.StallMessage,
			})
		}
		return true, false
	}

	providerID := ci.EffectiveProviderID()

	if action.DestroyProvider && providerID != "" && client != nil {
		if err := client.DestroyInstance(providerID); err != nil {
			slog.Warn("failed to destroy instance, deferring terminal status to next reconcile pass", "component", "reconcile", "instance", ci.ID, "provider", providerID, "error", err)
			return false, false
		}
	}

	if action.TerminalStatus != "" {
		if err := db.UpdateLaunchStatus(database, ci.ID, action.TerminalStatus, action.TerminationReason, action.StallMessage); err != nil {
			slog.Warn("failed to update instance status", "component", "reconcile", "instance", ci.ID, "status", action.TerminalStatus, "error", err)
			return false, false
		}
		op := oplog.OpLaunchTerminated
		if action.TerminalStatus == db.LaunchStatusFailed {
			op = oplog.OpLaunchLaunchFailed
		}
		oplog.Log(op, oplog.WithDetail(formatActionDetail(ci.ID, action)))
		if eventKind := actionEventKind(action.Kind); eventKind != "" {
			_ = db.InsertLifecycleEvent(database, &db.LifecycleEvent{
				EventKind: eventKind,
				LaunchID:  ci.ID,
				GPUSpec:   ci.GPUSpec,
				Detail:    action.StallMessage,
			})
		}
	}

	if action.ResetJobs {
		if resetCount, err := db.ResetLaunchJobs(database, ci.ID, action.AttemptOutcome); err != nil {
			slog.Warn("failed to reset jobs for instance", "component", "reconcile", "instance", ci.ID, "error", err)
		} else if resetCount > 0 {
			slog.Debug("reset jobs from instance to unplaced", "component", "reconcile", "count", resetCount, "instance", ci.ID)
		}
	} else if action.AttemptOutcome != "" {
		if err := db.CloseLaunchAttempts(database, ci.ID, action.AttemptOutcome); err != nil {
			slog.Warn("failed to close attempts for instance", "component", "reconcile", "instance", ci.ID, "error", err)
		}
	}

	return true, IsInstanceTerminal(action.TerminalStatus)
}

// String returns a stable name for use in oplog details, slog fields,
// and `%v` formatting. Falls back to the numeric form for unknown values.
func (k InstanceActionKind) String() string {
	switch k {
	case ActionNone:
		return "none"
	case ActionDisplayOnly:
		return "display_only"
	case ActionGraceExpired:
		return "grace_expired"
	case ActionDonorComplete:
		return "donor_complete"
	case ActionTerminationIntent:
		return "termination_intent"
	case ActionEmptyStatusTimeout:
		return "empty_status_timeout"
	case ActionBootstrapStalled:
		return "bootstrap_stalled"
	case ActionBootstrapComplete:
		return "bootstrap_complete"
	case ActionSetupStalled:
		return "setup_stalled"
	case ActionRunningStalled:
		return "running_stalled"
	case ActionIdleAfterReadyTimeout:
		return "idle_after_ready_timeout"
	case ActionProviderDead:
		return "provider_dead"
	case ActionSelfDestructFailed:
		return "self_destruct_failed"
	case ActionPause:
		return "pause"
	case ActionResume:
		return "resume"
	case ActionHedgeCull:
		return "hedge_cull"
	case ActionTerminalLivePhase:
		return "terminal_live_phase"
	default:
		return fmt.Sprintf("kind_%d", int(k))
	}
}

// formatActionDetail formats the per-action oplog detail string. Includes
// the provider-status snapshot captured by CheckInstance so post-mortems
// can identify status-classification bugs without re-fetching from the
// provider. Empty fields are omitted.
func formatActionDetail(launchID int64, action InstanceAction) string {
	parts := []string{fmt.Sprintf("launch_id=%d", launchID), fmt.Sprintf("action=%s", action.Kind)}
	if action.TerminationReason != "" {
		parts = append(parts, fmt.Sprintf("reason=%s", action.TerminationReason))
	}
	if action.ObservedProviderStatus != "" {
		parts = append(parts, fmt.Sprintf("status=%q", action.ObservedProviderStatus))
	}
	if action.ObservedProviderIntendedStatus != "" {
		parts = append(parts, fmt.Sprintf("intended=%q", action.ObservedProviderIntendedStatus))
	}
	if action.ObservedProviderStatusMsg != "" {
		parts = append(parts, fmt.Sprintf("status_msg=%q", action.ObservedProviderStatusMsg))
	}
	if action.StallMessage != "" {
		parts = append(parts, fmt.Sprintf("detail=%q", action.StallMessage))
	}
	return strings.Join(parts, " ")
}

// actionEventKind maps an InstanceActionKind to a lifecycle event kind constant.
func actionEventKind(kind InstanceActionKind) string {
	switch kind {
	case ActionBootstrapStalled:
		return db.EventReconcileBootstrapTimeout
	case ActionGraceExpired:
		return db.EventReconcileGraceExpired
	case ActionProviderDead:
		return db.EventReconcileProviderDead
	case ActionSelfDestructFailed:
		return db.EventReconcileSelfDestructFail
	case ActionEmptyStatusTimeout:
		return db.EventReconcileEmptyStatus
	case ActionDonorComplete:
		return db.EventReconcileDonorComplete
	case ActionTerminationIntent:
		return db.EventReconcileTerminationIntent
	case ActionBootstrapComplete:
		return db.EventReconcileBootstrapComplete
	case ActionSetupStalled:
		return db.EventReconcileSetupStall
	case ActionRunningStalled:
		return db.EventReconcileRunningStall
	case ActionPause:
		return db.EventReconcileProviderPaused
	case ActionResume:
		return db.EventReconcileProviderResumed
	case ActionHedgeCull:
		return db.EventReconcileHedgeCull
	case ActionTerminalLivePhase:
		return db.EventReconcileRunningStall
	default:
		return ""
	}
}
